### ISSUE TITLE
Not working in IIS

### ISSUE THREAD

**Issue by chadgallagher** [niphlod/ssis_dash#7]
The app seems to load at the server landing page, but as soon as you select a server to go it's specific page nothing loads, just a error message to refresh the page. See attached screen shot
![monitor error](https://cloud.githubusercontent.com/assets/10505364/15216733/59c03c06-1826-11e6-9dd9-a66fc62674a2.png)

**Comment by niphlod** [comment]
how is it configured ?

**Comment by chadgallagher** [comment]
This same configuration works if I just run web2py outside of IIS. The contents of the web2py folder is sitting in the wwwroot folder. Fast cgi has been setup correctly as well as the one config file. IIS User has been givin the correct permissions as well. Not sure why it is giving that error

**Comment by niphlod** [comment]
are you using IIS coupled with the source version and not the binary then ? Is it ready to reply under the root of the website ?

**Comment by chadgallagher** [comment]
It is the source version of web2py. It was extracted and them moved over the the root website folder

**Comment by chadgallagher** [comment]
I would think that if IIS can not access web2py or python correctly than the site would not load at all. It's loading in my case partially

**Comment by niphlod** [comment]
it really depends on a number of things. First and foremost, errors are browsable on localhost going to the admin app. If you are willing to send the error file to niphlod at gmail.com I'll be happy to scour it searching for the issue. BTW, how is your web.config ?

**Comment by niphlod** [comment]
(error files are stored into the applications/init/errors folder)

**Comment by chadgallagher** [comment]
I checked that earlier, and there is nothing in that folder

**Comment by niphlod** [comment]
ok, then it's a "managed" exception such as a "not found". Can you inspect via developer tools the XJR requests that are failing ?

**Comment by chadgallagher** [comment]
Not sure what tools you are referring to. I can see what it shows in fiddler

**Comment by niphlod** [comment]
I see IE from the screenshot. Usually hitting D12 opens them (the network tab is the relevant one in this case)

**Comment by chadgallagher** [comment]
![2016-05-13 10_50_50-10 1 14 38 - remote desktop connection](https://cloud.githubusercontent.com/assets/10505364/15251722/b46b2332-18f8-11e6-8354-251c8a01844f.png)

**Comment by niphlod** [comment]
Those seem perfectly fine requests (they seem legit, so it's not a "routing" issue). A 500 error though should be definitely logged into the "errors" folder. Can you open the first one (/init/rest_data/folders/***) in a separate tab ?

**Comment by chadgallagher** [comment]
if I look at the response body for that one it shows unable to execute query

**Comment by chadgallagher** [comment]
still nothing in the errors folder, not sure if that is because of IIS or not

**Comment by niphlod** [comment]
nope. every step clears a bit further where the error lies. I need to instrument better the interface for error reporting though. That tiny bit of error is returned whenever the config file doesn't have the correct connstring or if the query is failing or if the process can't access the queries/ dir. I didn't think to it first because you said outside of IIS everything works...
If you want to see the complete exception you can/should edit line 99 on models/helpers.py with "if 1:" and line 104 with "else:"   (basically removing the try: except: stanza)

**Comment by chadgallagher** [comment]
just made the changes to the helper file. Nothing changed. Now if I removed the 1 from line 99 I get a error (like I should) and am able to view it in the admin console

**Comment by niphlod** [comment]
without "1" though it'd be an exception of "syntax" .
Basically to avoid intercepting the original

```
def fetch_results(filepath, **kwargs):
    try:
        dbssis = DAL(INSTANCES_DICT[request.args(0)], migrate=False, attempts=1, driver_args={'timeout' : 5}, pool_size=2)
        with open(os.path.join(request.folder, 'queries', filepath)) as g:
            content = g.read()
        rtn = dbssis.executesql(content, **kwargs)
    except:
        raise HTTP(500, 'Unable to execute query')
    return rtn
```

should become

```
def fetch_results(filepath, **kwargs):
    if 1:
        dbssis = DAL(INSTANCES_DICT[request.args(0)], migrate=False, attempts=1, driver_args={'timeout' : 5}, pool_size=2)
        with open(os.path.join(request.folder, 'queries', filepath)) as g:
            content = g.read()
        rtn = dbssis.executesql(content, **kwargs)
    else:
        raise HTTP(500, 'Unable to execute query')
    return rtn
```

or, even better, 

```
def fetch_results(filepath, **kwargs):
    dbssis = DAL(INSTANCES_DICT[request.args(0)], migrate=False, attempts=1, driver_args={'timeout' : 5}, pool_size=2)
    with open(os.path.join(request.folder, 'queries', filepath)) as g:
        content = g.read()
    rtn = dbssis.executesql(content, **kwargs)
    return rtn
```

**Comment by chadgallagher** [comment]
ya the second one is the way I have it edited now. That does nothing. Let me try the third option. I wanted to remove the 1 to make sure that I still get actual errors and could open the web2py admin panel.

**Comment by chadgallagher** [comment]
Nothing changed, no errors, same message in the response body. I wonder if it is a permission issue

**Comment by niphlod** [comment]
ahem. there's something strange going on there. If you scour through the whole source code, "Unable to execute query" is only [there](https://github.com/niphlod/ssis_dash/search?utf8=%E2%9C%93&q=Unable+to+execute+query) . If you removed it, and the app is still returning it, it seems that you're not editing the right file ^_^

**Comment by chadgallagher** [comment]
the File looks right, the unable to execute query is in the response body from drilling down on that error in developer tools

![helpers_file](https://cloud.githubusercontent.com/assets/10505364/15254357/72d8be46-1904-11e6-8eb3-4cd105d5290b.png)

**Comment by chadgallagher** [comment]
the File looks right, the unable to execute query is in the response body from drilling down on that error in developer tools
![helpers_file](https://cloud.githubusercontent.com/assets/10505364/15254837/c6e66b62-1906-11e6-939b-1c93dc7cafda.png)

**Comment by niphlod** [comment]
the file may look right but somehow IIS is still executing "the old version" with "unable to execute query" in it. In order to avoid IIS "stubborness" in executing the old version, did you try issuing an iisreset command (i.e. stopping and starting the whole IIS) ?

**Comment by chadgallagher** [comment]
I have shut down the individual site and IIS as a whole each time I do something, not sure why it is still doing that

**Comment by niphlod** [comment]
Imho at this point it'd be better to figure out a time to establish a
remote session (teamviewer?)  to inspect better the issue. I'll be free in
two hours from now
Il 16 mag 2016 7:13 PM, "chadgallagher" notifications@github.com ha
scritto:

**Comment by chadgallagher** [comment]
looks like even though I had a bak file for helpers it was still trying to reference it. One removed I got some errors in the error folder. Seems like there is a issue with connecting with the SQL server.
`(dp1
S'output'
p2
S'<type \'exceptions.RuntimeError\'> Failure to connect, tried 1 times:\nTraceback (most recent call last):\n  File "C:\\inetpub\\wwwroot\\gluon\\packages\\dal\\pydal\\base.py", line 446, in __init__\n    self._adapter = ADAPTERS[self._dbname](**kwargs)\n  File "C:\\inetpub\\wwwroot\\gluon\\packages\\dal\\pydal\\adapters\\base.py", line 60, in __call__\n    obj = super(AdapterMeta, cls).__call__(*args, **kwargs)\n  File "C:\\inetpub\\wwwroot\\gluon\\packages\\dal\\pydal\\adapters\\mssql.py", line 159, in __init__\n    if do_connect: self.reconnect()\n  File "C:\\inetpub\\wwwroot\\gluon\\packages\\dal\\pydal\\connection.py", line 125, in reconnect\n    self.connection = f()\n  File "C:\\inetpub\\wwwroot\\gluon\\packages\\dal\\pydal\\adapters\\mssql.py", line 157, in connector\n    return self.driver.connect(cnxn, **driver_args)\n  File ".\\gluon\\contrib\\pypyodbc.py", line 2434, in __init__\n    self.connect(connectString, autocommit, ansi, timeout, unicode_results, readonly)\n  File ".\\gluon\\contrib\\pypyodbc.py", line 2483, in connect\n    check_success(self, ret)\n  File ".\\gluon\\contrib\\pypyodbc.py", line 988, in check_success\n    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)\n  File ".\\gluon\\contrib\\pypyodbc.py", line 966, in ctrl_err\n    raise DatabaseError(state,err_text)\nDatabaseError: (u\'28000\', u"[28000] [Microsoft][ODBC SQL Server Driver][SQL Server]Login failed for user \'servername\'.")\n'
p3
sS'layer'
p4
S'C:\\inetpub\\wwwroot\\applications\\init\\controllers/rest_data.py'
p5
sS'code'
p6`

**Comment by chadgallagher** [comment]
Seems that changing the default identity in the application pool worked. going to re-instate the original helper file as well.

**Comment by niphlod** [comment]
ok, can we close this then ?

**Comment by chadgallagher** [comment]
We sure can. It is up and running now in IIS perfectly 

Thanks for all your help

**Comment by niphlod** [comment]
ok, no problem. BTW: if you install pyodbc you'd get a performance improvement over the default driver (pypyodbc) which is a pure python module and used as a fallback

**Comment by chadgallagher** [comment]
I already have that installed when I was looking at yorek's build thanks.
